# Generated by Django 3.0.8 on 2020-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=20)),
                ('assigned_CSE', models.CharField(max_length=50)),
                ('visit_date', models.DateField()),
            ],
        ),
    ]
