# Generated by Django 3.0.8 on 2020-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uservisitdashboard', '0002_uservisit_doc_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='visit_completed',
            field=models.BooleanField(default=False),
        ),
    ]
